import avatar from "../../assets/img/Avatars.png";

export const alunos = [
  {
    firstName: "Eloisa",
    lastName: "Fernandes",
    username: "@elofer",
    status: "Active",
    email: "eloisafer16@gmail.com",
    phone: "123-456-7890",
    birthdate: "1990-01-01",
    course: "Computer Science",
    registration: "2021001",
    university: "Universidade de São Paulo",
    profileImage: avatar,
  },
  {
    firstName: "Marcos",
    lastName: "Augusto",
    username: "@maraug",
    status: "Offline",
    email: "emaraugust16@gmail.com",
    phone: "123-456-7860",
    birthdate: "1990-05-01",
    course: "History",
    registration: "2021001",
    university: "Universidade de São Paulo",
    profileImage: avatar,
  },
  {
    firstName: "Eloisa",
    lastName: "Fernandes",
    username: "@elofer",
    status: "Offline",
    email: "eloisafer16@gmail.com",
    phone: "123-456-7890",
    birthdate: "1990-01-01",
    course: "Computer Science",
    registration: "2021001",
    university: "Universidade de São Paulo",
    profileImage: avatar,
  },
  {
    firstName: "Eloisa",
    lastName: "Fernandes",
    username: "@elofer",
    status: "Wait",
    email: "eloisafer16@gmail.com",
    phone: "123-456-7890",
    birthdate: "1990-01-01",
    course: "Computer Science",
    registration: "2021001",
    university: "Universidade de São Paulo",
    profileImage: avatar,
  },
  {
    firstName: "Eloisa",
    lastName: "Fernandes",
    username: "@elofer",
    status: "Active",
    email: "eloisafer16@gmail.com",
    phone: "123-456-7890",
    birthdate: "1990-01-01",
    course: "Computer Science",
    registration: "2021001",
    university: "Universidade de São Paulo",
    profileImage: avatar,
  },
  {
    firstName: "Eloisa",
    lastName: "Fernandes",
    username: "@elofer",
    status: "Wait",
    email: "eloisafer16@gmail.com",
    phone: "123-456-7890",
    birthdate: "1990-01-01",
    course: "Computer Science",
    registration: "2021001",
    university: "Universidade de São Paulo",
    profileImage: avatar,
  },
];
