import avatar from "../../assets/img/Avatars.png";

export const alunos = [
  {
    nome: "Jane Cooper",
    username: "@jane",
    img: avatar,
    status: "Active",
    email: "jessica.hanson@example.com",
    birthday: "3/5/12",
  },
  {
    nome: "Wade Warren",
    username: "@wade",
    img: avatar,
    status: "Offline",
    email: "willie.jennings@example.com",
    birthday: "7/8/12",
  },
  {
    nome: "Jane Cooper",
    username: "@jane",
    img: avatar,
    status: "Active",
    email: "jessica.hanson@example.com",
    birthday: "3/5/12",
  },
  {
    nome: "Jane Cooper",
    username: "@jane",
    img: avatar,
    status: "Active",
    email: "jessica.hanson@example.com",
    birthday: "3/5/12",
  },
  {
    nome: "Jane Cooper",
    username: "@jane",
    img: avatar,
    status: "Offline",
    email: "jessica.hanson@example.com",
    birthday: "3/5/12",
  },
  {
    nome: "Jane Cooper",
    username: "@jane",
    img: avatar,
    status: "Active",
    email: "jessica.hanson@example.com",
    birthday: "3/5/12",
  },
  {
    nome: "Jane Cooper",
    username: "@jane",
    img: avatar,
    status: "Offline",
    email: "jessica.hanson@example.com",
    birthday: "3/5/12",
  },
  {
    nome: "Jane Cooper",
    username: "@jane",
    img: avatar,
    status: "Active",
    email: "jessica.hanson@example.com",
    birthday: "3/5/12",
  },
  {
    nome: "Jane Cooper",
    username: "@jane",
    img: avatar,
    status: "Wait",
    email: "jessica.hanson@example.com",
    birthday: "3/5/12",
  },
  {
    nome: "Jane Cooper",
    username: "@jane",
    img: avatar,
    status: "Active",
    email: "jessica.hanson@example.com",
    birthday: "3/5/12",
  },
  {
    nome: "Jane Cooper",
    username: "@jane",
    img: avatar,
    status: "Active",
    email: "jessica.hanson@example.com",
    birthday: "3/5/12",
  },
  {
    nome: "Jane Cooper",
    username: "@jane",
    img: avatar,
    status: "Wait",
    email: "jessica.hanson@example.com",
    birthday: "3/5/12",
  },
  {
    nome: "Jane Cooper",
    username: "@jane",
    img: avatar,
    status: "Active",
    email: "jessica.hanson@example.com",
    birthday: "3/5/12",
  },
  {
    nome: "Jane Cooper",
    username: "@jane",
    img: avatar,
    status: "Wait",
    email: "jessica.hanson@example.com",
    birthday: "3/5/12",
  },
  {
    nome: "Jane Cooper",
    username: "@jane",
    img: avatar,
    status: "Active",
    email: "jessica.hanson@example.com",
    birthday: "3/5/12",
  },
];
